
name: Build master

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:

  check_source:
    name: "Run code checks"
    uses: ./.github/workflows/_shared-check.yaml

  build_binaries:
    name: "Build shamir-msg"
    needs: [check_source]
    uses: ./.github/workflows/_shared-build.yaml
    with:
      ref: ${{ github.sha }}
      release: "snapshot"
      docker: true
      docker_repository: "pk910/shamir-msg"
      docker_tag_prefix: "master"
      additional_tags: "['master','master-latest']"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
