
name: Build Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version Number ('0.x.y')"
        required: true

permissions:
  contents: write

jobs:
  build_binaries:
    name: "Build shamir-msg"
    uses: ./.github/workflows/_shared-build.yaml
    with:
      ref: ${{ github.sha }}
      release: "v${{ inputs.version }}"
      docker: true
      docker_repository: "pk910/shamir-msg"
      docker_tag_prefix: "v${{ inputs.version }}"
      additional_tags: "['v${{ inputs.version }}','latest']"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  
  create_release:
    name: Create Release
    needs: [build_binaries]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 100
        ref: ${{ github.sha }}
    - name: "Generate release changelog"
      id: changelog
      run: |
        git fetch --tags
        prev_tag=$(git tag --sort=-version:refname | grep -e "^v[0-9.]*$" | head -n 1)
        echo "previous release: $prev_tag"
        if [ "$prev_tag" ]; then
          changelog=$(git log --oneline --no-decorate $prev_tag..HEAD)
        else
          changelog=$(git log --oneline --no-decorate)
        fi
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo " - ${changelog//$'\n'/$'\n' - }" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    # download build artifacts
    - name: "Download build artifacts"
      uses: actions/download-artifact@v4

    # create draft release
    - name: Create latest release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: true
        prerelease: false
        release_name: "v${{ inputs.version }}"
        tag_name: "v${{ inputs.version }}"
        body: |
          ### Major Changes
          - Add major changes here

          <details>
            <summary>Full changelog</summary>
          
          ### Changes
          ${{ steps.changelog.outputs.changelog }}
          </details>

          ### Release Artifacts
          | Release File  | Description |
          | ------------- | ------------- |
          | [shamir-msg-win64.exe](https://github.com/pk910/shamir-msg/releases/download/v${{ inputs.version }}/shamir-msg-win64.exe) | shamir-msg executable for windows/amd64 |
          | [shamir-msg-linux-amd64](https://github.com/pk910/shamir-msg/releases/download/v${{ inputs.version }}/shamir-msg-linux-amd64) | shamir-msg executable for linux/amd64 |
          | [shamir-msg-linux-arm64](https://github.com/pk910/shamir-msg/releases/download/v${{ inputs.version }}/shamir-msg-linux-arm64) | shamir-msg executable for linux/arm64 |
          | [shamir-msg-darwin-amd64](https://github.com/pk910/shamir-msg/releases/download/v${{ inputs.version }}/shamir-msg-darwin-amd64) | shamir-msg executable for macos/amd64 |
          | [shamir-msg-darwin-arm64](https://github.com/pk910/shamir-msg/releases/download/v${{ inputs.version }}/shamir-msg-darwin-arm64) | shamir-msg executable for macos/arm64 |
      env:
        GITHUB_TOKEN: ${{ github.token }}

    # generate & upload release artifacts
    - name: "Upload release artifact: shamir-msg-win64.exe"
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./shamir-msg_windows_amd64/shamir-msg.exe
        asset_name: shamir-msg-win64.exe
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: "Upload release artifact: shamir-msg-linux-amd64"
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./shamir-msg_linux_amd64/shamir-msg
        asset_name: shamir-msg-linux-amd64
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: "Upload release artifact: shamir-msg-linux-arm64"
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./shamir-msg_linux_arm64/shamir-msg
        asset_name: shamir-msg-linux-arm64
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: "Upload release artifact: shamir-msg-darwin-amd64"
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./shamir-msg_darwin_amd64/shamir-msg
        asset_name: shamir-msg-darwin-amd64
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: "Upload release artifact: shamir-msg-darwin-arm64"
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./shamir-msg_darwin_arm64/shamir-msg
        asset_name: shamir-msg-darwin-arm64
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ github.token }}
